version: 1

formatters:
  simple:
    format: '%(asctime)s - %(module)s - %(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  debug_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    maxBytes: 10485760  # 10MB
    backupCount: 20
    formatter: simple
    filename: debug.log

root:
  level: NOTSET
  handlers: [ console, debug_file ]